# Numpy tensor operations

## Tensor manipulations

In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()
d1 = 2
d2 = 3
d3 = 4
tf.executing_eagerly() 

True

In [2]:
# Utils functions
def print_array(x):
    if x.numpy().ndim <= 3:
        print('Tensor shape: {}\n{}-Tensor:\n{}\n'.format(x.numpy().shape, x.numpy().ndim, x))
    else:
        print('{}-Tensor shape: {}\n'.format(x.numpy().ndim, x.numpy().shape))

## Changing tensor shape

### Reshape 

tf.reshape : Gives a new shape to an array without changing its data

In [3]:
# 2D
x = tf.Variable(tf.random_uniform([d1, d2], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.reshape(x, [d2,d1]) # Transpose: interchange axis
print_array(y)

y = tf.reshape(x, [1,d1*d2]) # Flatten in axis 0 
print_array(y)

y = tf.reshape(x, [d1*d2, 1]) # Flatten in axis 1
print_array(y)

y = tf.reshape(x, [d1*d2]) # Flatten and remove dimensions equal to 1
print_array(y)

y = tf.reshape(x, [2,-1]) # Infer dimensions of axis 1 based on value of axis 0
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[7, 6, 5],
       [2, 2, 7]])>

Tensor shape: (3, 2)
2-Tensor:
[[7 6]
 [5 2]
 [2 7]]

Tensor shape: (1, 6)
2-Tensor:
[[7 6 5 2 2 7]]

Tensor shape: (6, 1)
2-Tensor:
[[7]
 [6]
 [5]
 [2]
 [2]
 [7]]

Tensor shape: (6,)
1-Tensor:
[7 6 5 2 2 7]

Tensor shape: (2, 3)
2-Tensor:
[[7 6 5]
 [2 2 7]]



In [4]:
# 3D
x = tf.Variable(tf.random_uniform([d1, d2, d3], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.reshape(x, [d3,d2,d1]) # Transpose: interchange axis
print_array(y)

y = tf.reshape(x, [1,d1*d2*d3]) # Flatten in axis 0 
print_array(y)

y = tf.reshape(x, [d1*d2*d3]) # Flatten and remove dimensions equal to 1
print_array(y)

y = tf.reshape(x, [2,-1]) # Infer dimensions of axis 1,2 based on value of axis 0
print_array(y)

y = tf.reshape(x, [2,4,-1]) # Infer dimensions of axis 2 based on value of axis 0,1
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[4, 8, 8, 7],
        [2, 2, 3, 7],
        [3, 1, 3, 1]],

       [[9, 2, 4, 5],
        [9, 6, 8, 3],
        [7, 8, 8, 8]]])>

Tensor shape: (4, 3, 2)
3-Tensor:
[[[4 8]
  [8 7]
  [2 2]]

 [[3 7]
  [3 1]
  [3 1]]

 [[9 2]
  [4 5]
  [9 6]]

 [[8 3]
  [7 8]
  [8 8]]]

Tensor shape: (1, 24)
2-Tensor:
[[4 8 8 7 2 2 3 7 3 1 3 1 9 2 4 5 9 6 8 3 7 8 8 8]]

Tensor shape: (24,)
1-Tensor:
[4 8 8 7 2 2 3 7 3 1 3 1 9 2 4 5 9 6 8 3 7 8 8 8]

Tensor shape: (2, 12)
2-Tensor:
[[4 8 8 7 2 2 3 7 3 1 3 1]
 [9 2 4 5 9 6 8 3 7 8 8 8]]

Tensor shape: (2, 4, 3)
3-Tensor:
[[[4 8 8]
  [7 2 2]
  [3 7 3]
  [1 3 1]]

 [[9 2 4]
  [5 9 6]
  [8 3 7]
  [8 8 8]]]



### Flatten 

tf.reshape : Returns a flattened array (when [-1] args)

In [5]:
# 2D
x = tf.Variable(tf.random_uniform([d1, d2], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.reshape(x, [-1])
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4, 3, 0],
       [8, 7, 3]])>

Tensor shape: (6,)
1-Tensor:
[4 3 0 8 7 3]



In [6]:
# 3D
x = tf.Variable(tf.random_uniform([d1, d2, d3], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.reshape(x, [-1])
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[7, 9, 5, 6],
        [7, 3, 1, 6],
        [4, 9, 8, 8]],

       [[1, 0, 5, 5],
        [0, 7, 0, 1],
        [3, 2, 3, 4]]])>

Tensor shape: (24,)
1-Tensor:
[7 9 5 6 7 3 1 6 4 9 8 8 1 0 5 5 0 7 0 1 3 2 3 4]



## Transpose-like operations

## Rollaxis

tf.roll : Roll the specified axis backwards, until it lies in a given position

In [8]:
# 3D
x = tf.Variable(tf.random_uniform([d1, d2, d3], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.roll(x, 2, 0) # Get axis 1 and roll backwards until position 0
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[2, 2, 1, 0],
        [3, 3, 0, 9],
        [0, 8, 5, 4]],

       [[8, 2, 0, 0],
        [5, 7, 8, 5],
        [2, 3, 1, 8]]])>

Tensor shape: (2, 3, 4)
3-Tensor:
[[[2 2 1 0]
  [3 3 0 9]
  [0 8 5 4]]

 [[8 2 0 0]
  [5 7 8 5]
  [2 3 1 8]]]



## Transpose

tf.transpose : Permute the dimensions of an array

In [7]:
# 2D
x = tf.Variable(tf.random_uniform([d1, d2], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.transpose(x) # Swap the two axis
print_array(y)

# 3D
x = tf.Variable(tf.random_uniform([d1, d2, d3], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.transpose(x) # Swap 0 <-> 2 axis leaving 1 unchanged
print_array(y)

# 4D
x = tf.Variable(tf.random_uniform([d1, d2, d3, 5], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.transpose(x) # Swap 0<->4 and 1<->3 axis
print_array(y)

# 5D
x = tf.Variable(tf.random_uniform([d1, d2, d3, 5, 6], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.transpose(x) # Swap 0<->5 and 1<->4 axis leaving 3 unchanged
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 5],
       [1, 1, 8]])>

Tensor shape: (3, 2)
2-Tensor:
[[0 1]
 [1 1]
 [5 8]]

Tensor shape: (2, 3, 4)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[2, 0, 5, 5],
        [8, 7, 1, 7],
        [9, 1, 1, 5]],

       [[1, 5, 6, 4],
        [8, 0, 4, 5],
        [0, 8, 3, 3]]])>

Tensor shape: (4, 3, 2)
3-Tensor:
[[[2 1]
  [8 8]
  [9 0]]

 [[0 5]
  [7 0]
  [1 8]]

 [[5 6]
  [1 4]
  [1 3]]

 [[5 4]
  [7 5]
  [5 3]]]

4-Tensor shape: (2, 3, 4, 5)

4-Tensor shape: (5, 4, 3, 2)

5-Tensor shape: (2, 3, 4, 5, 6)

5-Tensor shape: (6, 5, 4, 3, 2)



## Changing number of dimensions

### Expand_dims

tf.expand_dims : Expand the shape of an array

In [9]:
# 2D
x = tf.Variable(tf.random_uniform([d1, d2], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.expand_dims(x, axis=0) # Add a single-dimension axis at position 0
print_array(y)

y = tf.expand_dims(x, axis=1) # Add a single-dimension axis at position 1
print_array(y)

y = tf.expand_dims(x, axis=2) # Add a single-dimension axis at position 2
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[7, 4, 4],
       [2, 6, 5]])>

Tensor shape: (1, 2, 3)
3-Tensor:
[[[7 4 4]
  [2 6 5]]]

Tensor shape: (2, 1, 3)
3-Tensor:
[[[7 4 4]]

 [[2 6 5]]]

Tensor shape: (2, 3, 1)
3-Tensor:
[[[7]
  [4]
  [4]]

 [[2]
  [6]
  [5]]]



### Squeeze

tf.squeeze : Remove single-dimensional entries from the shape of an array

In [10]:
# 2D
x = tf.Variable(tf.random_uniform([d1, d2], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.squeeze(x) # Nothing happens because no 1-dims
print_array(y)

x = tf.Variable(tf.random_uniform([d1, d2, 1], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.squeeze(x) # Removes the single-dim
print_array(y)

x = tf.Variable(tf.random_uniform([1, d1, 1, d2, 1, 1, 1], 0, 10, dtype=tf.int32))
print_array(x)

y = tf.squeeze(x) # Removes every single-dim
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[6, 5, 6],
       [9, 1, 6]])>

Tensor shape: (2, 3)
2-Tensor:
[[6 5 6]
 [9 1 6]]

Tensor shape: (2, 3, 1)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 1) dtype=int32, numpy=
array([[[4],
        [2],
        [2]],

       [[1],
        [3],
        [9]]])>

Tensor shape: (2, 3)
2-Tensor:
[[4 2 2]
 [1 3 9]]

7-Tensor shape: (1, 2, 1, 3, 1, 1, 1)

Tensor shape: (2, 3)
2-Tensor:
[[1 9 3]
 [3 1 3]]



## Joining tensors

### Concatenate

tf.concat : Join a sequence of tensors along an existing axis

In [12]:
# 2D
x1 = tf.Variable(tf.random_uniform([3, d2], 0, 10, dtype=tf.int32))
print_array(x1)
x2 = tf.Variable(tf.random_uniform([4, d2], 0, 10, dtype=tf.int32))
print_array(x2)

y = tf.concat([x1,x2], axis=0)
print_array(y)

# 3D
x1 = tf.Variable(tf.random_uniform([d1, d2, 4], 0, 10, dtype=tf.int32))
print_array(x1)
x2 = tf.Variable(tf.random_uniform([d1, d2, 3], 0, 10, dtype=tf.int32))
print_array(x2)

y = tf.concat([x1,x2], axis=2)
print_array(y)

Tensor shape: (3, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 2, 7],
       [4, 9, 0],
       [1, 9, 1]])>

Tensor shape: (4, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[2, 0, 3],
       [2, 7, 5],
       [7, 0, 3],
       [5, 9, 4]])>

Tensor shape: (7, 3)
2-Tensor:
[[0 2 7]
 [4 9 0]
 [1 9 1]
 [2 0 3]
 [2 7 5]
 [7 0 3]
 [5 9 4]]

Tensor shape: (2, 3, 4)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=int32, numpy=
array([[[1, 3, 0, 7],
        [3, 7, 7, 3],
        [5, 1, 2, 4]],

       [[6, 6, 4, 9],
        [7, 7, 4, 7],
        [5, 8, 0, 5]]])>

Tensor shape: (2, 3, 3)
3-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[1, 7, 4],
        [3, 1, 7],
        [5, 7, 3]],

       [[8, 7, 6],
        [7, 6, 7],
        [3, 9, 3]]])>

Tensor shape: (2, 3, 7)
3-Tensor:
[[[1 3 0 7 1 7 4]
  [3 7 7 3 3 1 7]
  [5 1 2 4 5 7 3]]

 [[6 6 4 9 8 7 6]
  [7 7 4 7 7 6 7]
  [5 8 0 5 3 9 3

## Stack

tf.stack : Join a sequence of tensors along a new axis

In [11]:
# 2D
x1 = tf.Variable(tf.random_uniform([d2, d3], 0, 10, dtype=tf.int32))
print_array(x1)
x2 = tf.Variable(tf.random_uniform([d2, d3], 0, 10, dtype=tf.int32))
print_array(x2)

y = tf.stack([x1,x2], axis=0) # Stack the tensors over axis 0
print_array(y)

y = tf.stack([x1,x2], axis=1) # Stack the tensors over axis 1
print_array(y)

y = tf.stack([x1,x2], axis=2) # Stack the tensors over axis 2
print_array(y)

Tensor shape: (3, 4)
2-Tensor:
<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[5, 1, 5, 6],
       [8, 8, 6, 9],
       [2, 1, 3, 7]])>

Tensor shape: (3, 4)
2-Tensor:
<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[1, 0, 1, 5],
       [7, 7, 2, 2],
       [3, 0, 8, 4]])>

Tensor shape: (2, 3, 4)
3-Tensor:
[[[5 1 5 6]
  [8 8 6 9]
  [2 1 3 7]]

 [[1 0 1 5]
  [7 7 2 2]
  [3 0 8 4]]]

Tensor shape: (3, 2, 4)
3-Tensor:
[[[5 1 5 6]
  [1 0 1 5]]

 [[8 8 6 9]
  [7 7 2 2]]

 [[2 1 3 7]
  [3 0 8 4]]]

Tensor shape: (3, 4, 2)
3-Tensor:
[[[5 1]
  [1 0]
  [5 1]
  [6 5]]

 [[8 7]
  [8 7]
  [6 2]
  [9 2]]

 [[2 3]
  [1 0]
  [3 8]
  [7 4]]]



## Splitting tensors

### Split

tf.split : Split a tensor into multiple tensors

In [13]:
# 2D
x1 = tf.Variable(tf.random_uniform([d1, d2], 0, 10, dtype=tf.int32))
print_array(x1)

ys = tf.split(x1, num_or_size_splits=2)
for y in ys:
    print_array(y)
    
# 3D
x1 = tf.Variable(tf.random_uniform([d3, d2, d1], 0, 10, dtype=tf.int32))
print_array(x1)

ys = tf.split(x1, num_or_size_splits=2) # 2 splits over axis 0
for y in ys:
    print_array(y)
    
ys = tf.split(x1, num_or_size_splits=4) # 4 splits over axis 0
for y in ys:
    print_array(y)

Tensor shape: (2, 3)
2-Tensor:
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[7, 1, 3],
       [4, 2, 8]])>

Tensor shape: (1, 3)
2-Tensor:
[[7 1 3]]

Tensor shape: (1, 3)
2-Tensor:
[[4 2 8]]

Tensor shape: (4, 3, 2)
3-Tensor:
<tf.Variable 'Variable:0' shape=(4, 3, 2) dtype=int32, numpy=
array([[[3, 3],
        [5, 3],
        [7, 0]],

       [[5, 2],
        [0, 5],
        [8, 2]],

       [[8, 9],
        [9, 0],
        [2, 7]],

       [[9, 7],
        [4, 1],
        [0, 4]]])>

Tensor shape: (2, 3, 2)
3-Tensor:
[[[3 3]
  [5 3]
  [7 0]]

 [[5 2]
  [0 5]
  [8 2]]]

Tensor shape: (2, 3, 2)
3-Tensor:
[[[8 9]
  [9 0]
  [2 7]]

 [[9 7]
  [4 1]
  [0 4]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[3 3]
  [5 3]
  [7 0]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[5 2]
  [0 5]
  [8 2]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[8 9]
  [9 0]
  [2 7]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[9 7]
  [4 1]
  [0 4]]]

