# Numpy tensor operations

## Tensor linear algebra

In [1]:
import numpy as np
d1 = 2
d2 = 3
d3 = 4

In [2]:
# Utils functions

def print_array(x):
    if x.ndim <= 3:
        print('Tensor shape: {}\n{}-Tensor:\n{}\n'.format(x.shape, x.ndim, x))
    else:
        print('{}-Tensor shape: {}\n'.format(x.ndim, x.shape))

## Tensor products

### Dot

numpy.dot : Dot product of two tensors

 - "a" and "b" are 1-D Tensors -> inner product of tensors
 - "a" and "b" are 2-D Tensors -> matrix multiplication (better matmul or "@" overload)
 - If either "a" or "b" are scalars -> multiply scalar times tensor (better multiply or "*" overload)
 - If "a" N-D tensor and "b" 1-D tensor -> sum product over the last axis of "a" and "b"
 - If "a" N-D tensor and "b" M-D tensor where M >= 2 -> sum product over the last axis of "a" and the second-to-last axis of "b"

In [3]:
# "a" and "b" are 1-D Tensors
print('"a" and "b" are 1-D Tensors -> inner product of tensors')
x1 = np.random.randint(10, size=(d1))
print_array(x1)
x2 = np.random.randint(10, size=(d1))
print_array(x2)
print('inner product of tensors')
y = np.dot(x1,x2) # inner product of tensors
print_array(y)

# "a" and "b" are 2-D Tensors
print('"a" and "b" are 2-D Tensors -> matrix multiplication')
x1 = np.random.randint(10, size=(2, 2))
print_array(x1)
x2 = np.random.randint(10, size=(2, 2))
print_array(x2)
print('matrix multiplication')
y = np.dot(x1,x2) # matrix multiplication (better matmul or "@" overload)
print_array(y)

# If either "a" or "b" are scalars
print('If either "a" or "b" are scalars -> multiply scalar times tensor')
x1 = 2
x2 = np.random.randint(10, size=(d1))
print_array(x2)
print('multiply scalar times tensor')
y = np.dot(x1,x2) # multiply scalar times tensor (better multiply or "*" overload)
print_array(y)

# If "a" N-D tensor and "b" 1-D tensor
print('If "a" N-D tensor and "b" 1-D tensor -> sum product over the last axis of "a" and "b"')
x1 = np.random.randint(10, size=(d2))
print_array(x1)
x2 = np.random.randint(10, size=(d2,d3))
print_array(x2)
print('sum product over the last axis of "a" and "b"')
y = np.dot(x1,x2) # sum product over the last axis of "a" and "b"
print_array(y)

# If "a" N-D tensor and "b" M-D tensor where M >= 2
print('If "a" N-D tensor and "b" M-D tensor where M >= 2 -> sum product over the last axis of "a" and the second-to-last axis of "b"')
x1 = np.random.randint(10, size=(d1, d2))
print_array(x1)
x2 = np.random.randint(10, size=(d1, d2, d3))
print_array(x2)
print('sum product over the last axis of "a" and the second-to-last axis of "b"')
y = np.dot(x1,x2) # sum product over the last axis of "a" and the second-to-last axis of "b"
print_array(y)

"a" and "b" are 1-D Tensors -> inner product of tensors
Tensor shape: (2,)
1-Tensor:
[9 3]

Tensor shape: (2,)
1-Tensor:
[7 8]

inner product of tensors
Tensor shape: ()
0-Tensor:
87

"a" and "b" are 2-D Tensors -> matrix multiplication
Tensor shape: (2, 2)
2-Tensor:
[[5 1]
 [9 9]]

Tensor shape: (2, 2)
2-Tensor:
[[0 9]
 [8 7]]

matrix multiplication
Tensor shape: (2, 2)
2-Tensor:
[[  8  52]
 [ 72 144]]

If either "a" or "b" are scalars -> multiply scalar times tensor
Tensor shape: (2,)
1-Tensor:
[4 3]

multiply scalar times tensor
Tensor shape: (2,)
1-Tensor:
[8 6]

If "a" N-D tensor and "b" 1-D tensor -> sum product over the last axis of "a" and "b"
Tensor shape: (3,)
1-Tensor:
[9 0 9]

Tensor shape: (3, 4)
2-Tensor:
[[6 3 5 7]
 [5 6 6 4]
 [3 5 9 5]]

sum product over the last axis of "a" and "b"
Tensor shape: (4,)
1-Tensor:
[ 81  72 126 108]

If "a" N-D tensor and "b" M-D tensor where M >= 2 -> sum product over the last axis of "a" and the second-to-last axis of "b"
Tensor shape: (2

### Inner

numpy.inner : Inner product of two tensors

In [4]:
# "a" and "b" are 1-D Tensors
print('"a" and "b" are 1-D Tensors -> inner product of tensors')
x1 = np.random.randint(10, size=(d1))
print_array(x1)
x2 = np.random.randint(10, size=(d1))
print_array(x2)
print('inner product of tensors')
y = np.inner(x1,x2) # inner product of tensors
print_array(y)

# "a" and "b" are 1-D Tensors
print('"a" 1-D tensor and "b" N-D-Tensor -> sum product over the last axes')
x1 = np.random.randint(10, size=(d1, d2, d3))
print_array(x1)
x2 = np.arange(4)
print_array(x2)
print('inner product of tensors with sum product over the last axes')
y = np.inner(x1,x2) # inner product of tensors
print_array(y)

"a" and "b" are 1-D Tensors -> inner product of tensors
Tensor shape: (2,)
1-Tensor:
[4 7]

Tensor shape: (2,)
1-Tensor:
[5 9]

inner product of tensors
Tensor shape: ()
0-Tensor:
83

"a" 1-D tensor and "b" N-D-Tensor -> sum product over the last axes
Tensor shape: (2, 3, 4)
3-Tensor:
[[[8 8 0 1]
  [8 2 9 2]
  [5 2 9 3]]

 [[0 8 8 3]
  [6 4 2 5]
  [8 8 1 5]]]

Tensor shape: (4,)
1-Tensor:
[0 1 2 3]

inner product of tensors with sum product over the last axes
Tensor shape: (2, 3)
2-Tensor:
[[11 26 29]
 [33 23 25]]



### Outer

numpy.outer : Outer product of two tensors

In [5]:
# "a" and "b" are 1-D Tensors
print('"a" and "b" are 1-D Tensors -> outer product of tensors')
x1 = np.random.randint(10, size=(d1))
print_array(x1)
x2 = np.random.randint(10, size=(d1))
print_array(x2)
print('outer product of tensors')
y = np.outer(x1,x2) # outer product of tensors
print_array(y)

# "a" and "b" are 2-D Tensors
print('"a" and "b" are 2-D Tensors -> outer product of tensors')
x1 = np.random.randint(10, size=(d1,d2))
print_array(x1)
x2 = np.random.randint(10, size=(d1,d2))
print_array(x2)
print('outer product of tensors')
y = np.outer(x1,x2) # outer product of tensors
print_array(y)

"a" and "b" are 1-D Tensors -> outer product of tensors
Tensor shape: (2,)
1-Tensor:
[7 2]

Tensor shape: (2,)
1-Tensor:
[6 6]

outer product of tensors
Tensor shape: (2, 2)
2-Tensor:
[[42 42]
 [12 12]]

"a" and "b" are 2-D Tensors -> outer product of tensors
Tensor shape: (2, 3)
2-Tensor:
[[4 0 0]
 [7 5 3]]

Tensor shape: (2, 3)
2-Tensor:
[[5 9 1]
 [8 4 9]]

outer product of tensors
Tensor shape: (6, 6)
2-Tensor:
[[20 36  4 32 16 36]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [35 63  7 56 28 63]
 [25 45  5 40 20 45]
 [15 27  3 24 12 27]]



### Matmul

numpy.matmul : Matrix product of two tensors

In [6]:
# "a" and "b" are 2-D Tensors
print('"a" and "b" are 2-D Tensors -> matrix multiplication')
x1 = np.random.randint(10, size=(d1,d2))
print_array(x1)
x2 = np.random.randint(10, size=(d2,d1))
print_array(x2)
print('matrix multiplication')
y = np.matmul(x1,x2) # outer product of tensors
print_array(y)

"a" and "b" are 2-D Tensors -> matrix multiplication
Tensor shape: (2, 3)
2-Tensor:
[[0 9 0]
 [9 6 1]]

Tensor shape: (3, 2)
2-Tensor:
[[1 3]
 [7 5]
 [8 2]]

matrix multiplication
Tensor shape: (2, 2)
2-Tensor:
[[63 45]
 [59 59]]



### Tensordot 

numpy.tensordot : Compute tensor dot product along specified axes for tensors >= 1-D

 - axes = 0 : tensor product (a x b)
 - axes = 1 : tensor dot product (a . b)
 - axes = 2 : tensor double contraction (a : b)

In [7]:
print('axes = 0 : tensor product (a x b)')
x1 = np.random.randint(10, size=(d1,d2))
print_array(x1)
x2 = np.random.randint(10, size=(d1,d2))
print_array(x2)
print('tensor product (a x b)')
y = np.tensordot(x1, x2, axes=0) 
print_array(y)

print('axes = 1 : tensor dot product (a . b)')
x1 = np.random.randint(10, size=(d1, d2))
print_array(x1)
x2 = np.random.randint(10, size=(d2, d1))
print_array(x2)
print('tensor dot product (a . b)')
y = np.tensordot(x1, x2, axes=1)
print_array(y)

print('axes = 2 : tensor double contraction (a : b)')
x1 = np.random.randint(10, size=(d1,d2))
print_array(x1)
x2 = np.random.randint(10, size=(d1,d2))
print_array(x2)
print('tensor double contraction (a : b)')
y = np.tensordot(x1, x2, axes=2)
print_array(y)

axes = 0 : tensor product (a x b)
Tensor shape: (2, 3)
2-Tensor:
[[8 3 8]
 [5 2 2]]

Tensor shape: (2, 3)
2-Tensor:
[[5 6 0]
 [5 9 3]]

tensor product (a x b)
4-Tensor shape: (2, 3, 2, 3)

axes = 1 : tensor dot product (a . b)
Tensor shape: (2, 3)
2-Tensor:
[[1 3 2]
 [2 1 4]]

Tensor shape: (3, 2)
2-Tensor:
[[9 0]
 [0 3]
 [0 2]]

tensor dot product (a . b)
Tensor shape: (2, 2)
2-Tensor:
[[ 9 13]
 [18 11]]

axes = 2 : tensor double contraction (a : b)
Tensor shape: (2, 3)
2-Tensor:
[[9 1 6]
 [4 9 9]]

Tensor shape: (2, 3)
2-Tensor:
[[7 4 4]
 [6 4 0]]

tensor double contraction (a : b)
Tensor shape: ()
0-Tensor:
151

