# Numpy tensor operations

## Tensor manipulations

In [1]:
import numpy as np
d1 = 2
d2 = 3
d3 = 4

In [2]:
# Utils functions

def print_array(x):
    if x.ndim <= 3:
        print('Tensor shape: {}\n{}-Tensor:\n{}\n'.format(x.shape, x.ndim, x))
    else:
        print('{}-Tensor shape: {}\n'.format(x.ndim, x.shape))

## Changing tensor shape

### Reshape 

numpy.reshape : Gives a new shape to an array without changing its data

In [3]:
# 2D
x = np.random.randint(10, size=(d1, d2))
print_array(x)

y = np.reshape(x, [d2,d1]) # Transpose: interchange axis
print_array(y)

y = np.reshape(x, [1,d1*d2]) # Flatten in axis 0 
print_array(y)

y = np.reshape(x, [d1*d2, 1]) # Flatten in axis 1
print_array(y)

y = np.reshape(x, [d1*d2]) # Flatten and remove dimensions equal to 1
print_array(y)

y = np.reshape(x, [2,-1]) # Infer dimensions of axis 1 based on value of axis 0
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[9 8 4]
 [3 3 7]]

Tensor shape: (3, 2)
2-Tensor:
[[9 8]
 [4 3]
 [3 7]]

Tensor shape: (1, 6)
2-Tensor:
[[9 8 4 3 3 7]]

Tensor shape: (6, 1)
2-Tensor:
[[9]
 [8]
 [4]
 [3]
 [3]
 [7]]

Tensor shape: (6,)
1-Tensor:
[9 8 4 3 3 7]

Tensor shape: (2, 3)
2-Tensor:
[[9 8 4]
 [3 3 7]]



In [4]:
# 3D
x = np.random.randint(10, size=(d1, d2, d3))
print_array(x)

y = np.reshape(x, [d3,d2,d1]) # Transpose: interchange axis
print_array(y)

y = np.reshape(x, [1,d1*d2*d3]) # Flatten in axis 0 
print_array(y)

y = np.reshape(x, [d1*d2*d3]) # Flatten and remove dimensions equal to 1
print_array(y)

y = np.reshape(x, [2,-1]) # Infer dimensions of axis 1,2 based on value of axis 0
print_array(y)

y = np.reshape(x, [2,4,-1]) # Infer dimensions of axis 2 based on value of axis 0,1
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
[[[5 8 2 2]
  [1 1 3 7]
  [8 2 9 7]]

 [[6 7 8 3]
  [1 0 5 5]
  [2 9 2 1]]]

Tensor shape: (4, 3, 2)
3-Tensor:
[[[5 8]
  [2 2]
  [1 1]]

 [[3 7]
  [8 2]
  [9 7]]

 [[6 7]
  [8 3]
  [1 0]]

 [[5 5]
  [2 9]
  [2 1]]]

Tensor shape: (1, 24)
2-Tensor:
[[5 8 2 2 1 1 3 7 8 2 9 7 6 7 8 3 1 0 5 5 2 9 2 1]]

Tensor shape: (24,)
1-Tensor:
[5 8 2 2 1 1 3 7 8 2 9 7 6 7 8 3 1 0 5 5 2 9 2 1]

Tensor shape: (2, 12)
2-Tensor:
[[5 8 2 2 1 1 3 7 8 2 9 7]
 [6 7 8 3 1 0 5 5 2 9 2 1]]

Tensor shape: (2, 4, 3)
3-Tensor:
[[[5 8 2]
  [2 1 1]
  [3 7 8]
  [2 9 7]]

 [[6 7 8]
  [3 1 0]
  [5 5 2]
  [9 2 1]]]



### Ravel 

numpy.ravel : Returns a flattened array

ndarray.flatten : In-place variation

In [5]:
# 2D
x = np.random.randint(10, size=(d1, d2))
print_array(x)

y = np.ravel(x)
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[8 5 8]
 [2 6 0]]

Tensor shape: (6,)
1-Tensor:
[8 5 8 2 6 0]



In [6]:
# 3D
x = np.random.randint(10, size=(d1, d2, d3))
print_array(x)

y = np.ravel(x)
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
[[[4 7 3 7]
  [8 5 9 3]
  [6 9 4 4]]

 [[5 2 4 6]
  [6 7 8 8]
  [0 0 1 1]]]

Tensor shape: (24,)
1-Tensor:
[4 7 3 7 8 5 9 3 6 9 4 4 5 2 4 6 6 7 8 8 0 0 1 1]



## Transpose-like operations

## Moveaxis

numpy.moveaxis : Gives a new shape to an array without changing its data

In [7]:
# 2D
x = np.random.randint(10, size=(d1, d2))
print_array(x)

y = np.moveaxis(a=x, source=0, destination=1) # Transpose
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[1 2 9]
 [8 5 1]]

Tensor shape: (3, 2)
2-Tensor:
[[1 8]
 [2 5]
 [9 1]]



## Rollaxis

numpy.rollaxis : Roll the specified axis backwards, until it lies in a given position

In [8]:
# 3D
x = np.random.randint(10, size=(d1, d2, d3))
print_array(x)

y = np.rollaxis(x, 2, 0) # Get axis 1 and roll backwards until position 0
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
[[[3 0 4 1]
  [0 7 7 8]
  [1 3 5 0]]

 [[9 2 2 7]
  [6 6 6 0]
  [7 6 9 7]]]

Tensor shape: (4, 2, 3)
3-Tensor:
[[[3 0 1]
  [9 6 7]]

 [[0 7 3]
  [2 6 6]]

 [[4 7 5]
  [2 6 9]]

 [[1 8 0]
  [7 0 7]]]



## Swapaxes

numpy.swapaxes : Interchange two axis of an array

In [9]:
# 3D
x = np.random.randint(10, size=(d1, d2, d3))
print_array(x)

y = np.swapaxes(a=x, axis1=2, axis2=0) # Swap axis 2 <-> 0, left axis 1 unchanged
print_array(y)

Tensor shape: (2, 3, 4)
3-Tensor:
[[[5 6 0 5]
  [9 6 4 1]
  [7 1 3 6]]

 [[5 8 5 8]
  [2 9 3 8]
  [9 3 2 4]]]

Tensor shape: (4, 3, 2)
3-Tensor:
[[[5 5]
  [9 2]
  [7 9]]

 [[6 8]
  [6 9]
  [1 3]]

 [[0 5]
  [4 3]
  [3 2]]

 [[5 8]
  [1 8]
  [6 4]]]



## Transpose

numpy.transpose : Permute the dimensions of an array

In [12]:
# 2D
x = np.random.randint(10, size=(d1, d2)) 
print_array(x)

y = np.transpose(x) # Swap the two axis
print_array(y)

# 3D
x = np.random.randint(10, size=(d1, d2, d3))
print_array(x)

y = np.transpose(x) # Swap 0 <-> 2 axis leaving 1 unchanged
print_array(y)

# 4D
x = np.random.randint(10, size=(d1, d2, d3, 5)) 
print_array(x)

y = np.transpose(x) # Swap 0<->4 and 1<->3 axis
print_array(y)

# 5D
x = np.random.randint(10, size=(d1, d2, d3, 5, 6)) 
print_array(x)

y = np.transpose(x) # Swap 0<->5 and 1<->4 axis leaving 3 unchanged
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[1 6 0]
 [4 9 2]]

Tensor shape: (3, 2)
2-Tensor:
[[1 4]
 [6 9]
 [0 2]]

Tensor shape: (2, 3, 4)
3-Tensor:
[[[8 5 1 1]
  [5 6 1 5]
  [8 5 2 3]]

 [[2 7 7 1]
  [3 6 8 9]
  [3 8 4 9]]]

Tensor shape: (4, 3, 2)
3-Tensor:
[[[8 2]
  [5 3]
  [8 3]]

 [[5 7]
  [6 6]
  [5 8]]

 [[1 7]
  [1 8]
  [2 4]]

 [[1 1]
  [5 9]
  [3 9]]]

4-Tensor shape: (2, 3, 4, 5)

4-Tensor shape: (5, 4, 3, 2)

5-Tensor shape: (2, 3, 4, 5, 6)

5-Tensor shape: (6, 5, 4, 3, 2)



## Changing number of dimensions

### Expand_dims

numpy.expand_dims : Expand the shape of an array

In [16]:
# 2D
x = np.random.randint(10, size=(d1, d2))
print_array(x)

y = np.expand_dims(x, axis=0) # Add a single-dimension axis at position 0
print_array(y)

y = np.expand_dims(x, axis=1) # Add a single-dimension axis at position 1
print_array(y)

y = np.expand_dims(x, axis=2) # Add a single-dimension axis at position 2
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[6 5 1]
 [3 4 1]]

Tensor shape: (1, 2, 3)
3-Tensor:
[[[6 5 1]
  [3 4 1]]]

Tensor shape: (2, 1, 3)
3-Tensor:
[[[6 5 1]]

 [[3 4 1]]]

Tensor shape: (2, 3, 1)
3-Tensor:
[[[6]
  [5]
  [1]]

 [[3]
  [4]
  [1]]]



### Squeeze

numpy.squeeze : Remove single-dimensional entries from the shape of an array

In [21]:
# 2D
x = np.random.randint(10, size=(d1, d2))
print_array(x)

y = np.squeeze(x) # Nothing happens because no 1-dims
print_array(y)

x = np.random.randint(10, size=(d1, d2, 1))
print_array(x)

y = np.squeeze(x) # Removes the single-dim
print_array(y)

x = np.random.randint(10, size=(1, d1, 1, d2, 1, 1, 1))
print_array(x)

y = np.squeeze(x) # Removes every single-dim
print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[9 4 0]
 [9 5 0]]

Tensor shape: (2, 3)
2-Tensor:
[[9 4 0]
 [9 5 0]]

Tensor shape: (2, 3, 1)
3-Tensor:
[[[3]
  [8]
  [1]]

 [[1]
  [3]
  [3]]]

Tensor shape: (2, 3)
2-Tensor:
[[3 8 1]
 [1 3 3]]

7-Tensor shape: (1, 2, 1, 3, 1, 1, 1)

Tensor shape: (2, 3)
2-Tensor:
[[0 4 5]
 [3 7 8]]



## Joining tensors

### Concatenate

numpy.concatenate : Join a sequence of tensors along an existing axis

In [32]:
# 2D
x1 = np.random.randint(10, size=(3, d2))
print_array(x1)
x2 = np.random.randint(10, size=(4, d2))
print_array(x2)

y = np.concatenate([x1,x2], axis=0)
print_array(y)

# 3D
x1 = np.random.randint(10, size=(d1, d2, 4))
print_array(x1)
x2 = np.random.randint(10, size=(d1, d2, 3))
print_array(x2)

y = np.concatenate([x1,x2], axis=2)
print_array(y)

Tensor shape: (3, 3)
2-Tensor:
[[3 2 0]
 [9 5 2]
 [3 1 9]]

Tensor shape: (4, 3)
2-Tensor:
[[7 8 3]
 [7 9 2]
 [0 0 4]
 [2 5 3]]

Tensor shape: (7, 3)
2-Tensor:
[[3 2 0]
 [9 5 2]
 [3 1 9]
 [7 8 3]
 [7 9 2]
 [0 0 4]
 [2 5 3]]

Tensor shape: (2, 3, 4)
3-Tensor:
[[[7 3 8 2]
  [1 7 5 2]
  [9 7 2 3]]

 [[5 3 4 6]
  [4 7 6 7]
  [3 5 0 1]]]

Tensor shape: (2, 3, 3)
3-Tensor:
[[[3 5 5]
  [9 6 0]
  [3 1 2]]

 [[9 8 1]
  [0 2 5]
  [4 4 4]]]

Tensor shape: (2, 3, 7)
3-Tensor:
[[[7 3 8 2 3 5 5]
  [1 7 5 2 9 6 0]
  [9 7 2 3 3 1 2]]

 [[5 3 4 6 9 8 1]
  [4 7 6 7 0 2 5]
  [3 5 0 1 4 4 4]]]



## Stack

numpy.stack : Join a sequence of tensors along a new axis

In [41]:
# 2D
x1 = np.random.randint(10, size=(d2, d3))
print_array(x1)
x2 = np.random.randint(10, size=(d2, d3))
print_array(x2)

y = np.stack([x1,x2], axis=0) # Stack the tensors over axis 0
print_array(y)

y = np.stack([x1,x2], axis=1) # Stack the tensors over axis 1
print_array(y)

y = np.stack([x1,x2], axis=2) # Stack the tensors over axis 2
print_array(y)

Tensor shape: (3, 4)
2-Tensor:
[[4 3 8 1]
 [9 2 3 9]
 [1 7 2 1]]

Tensor shape: (3, 4)
2-Tensor:
[[9 5 1 5]
 [7 6 1 8]
 [4 3 9 2]]

Tensor shape: (2, 3, 4)
3-Tensor:
[[[4 3 8 1]
  [9 2 3 9]
  [1 7 2 1]]

 [[9 5 1 5]
  [7 6 1 8]
  [4 3 9 2]]]

Tensor shape: (3, 2, 4)
3-Tensor:
[[[4 3 8 1]
  [9 5 1 5]]

 [[9 2 3 9]
  [7 6 1 8]]

 [[1 7 2 1]
  [4 3 9 2]]]

Tensor shape: (3, 4, 2)
3-Tensor:
[[[4 9]
  [3 5]
  [8 1]
  [1 5]]

 [[9 7]
  [2 6]
  [3 1]
  [9 8]]

 [[1 4]
  [7 3]
  [2 9]
  [1 2]]]



## Splitting tensors

### Split

numpy.split : Split a tensor into multiple tensors

In [59]:
# 2D
x1 = np.random.randint(10, size=(d1, d2))
print_array(x1)

ys = np.split(x1, indices_or_sections=2)
for y in ys:
    print_array(y)
    
    
# 3D
x1 = np.random.randint(10, size=(d3, d2, d1))
print_array(x1)

ys = np.split(x1, indices_or_sections=2) # 2 splits over axis 0
for y in ys:
    print_array(y)
    
ys = np.split(x1, indices_or_sections=4) # 4 splits over axis 0
for y in ys:
    print_array(y)

Tensor shape: (2, 3)
2-Tensor:
[[5 7 0]
 [7 4 0]]

Tensor shape: (1, 3)
2-Tensor:
[[5 7 0]]

Tensor shape: (1, 3)
2-Tensor:
[[7 4 0]]

Tensor shape: (4, 3, 2)
3-Tensor:
[[[4 2]
  [4 2]
  [7 1]]

 [[3 3]
  [5 5]
  [3 2]]

 [[2 9]
  [3 9]
  [4 3]]

 [[2 0]
  [3 9]
  [7 5]]]

Tensor shape: (2, 3, 2)
3-Tensor:
[[[4 2]
  [4 2]
  [7 1]]

 [[3 3]
  [5 5]
  [3 2]]]

Tensor shape: (2, 3, 2)
3-Tensor:
[[[2 9]
  [3 9]
  [4 3]]

 [[2 0]
  [3 9]
  [7 5]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[4 2]
  [4 2]
  [7 1]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[3 3]
  [5 5]
  [3 2]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[2 9]
  [3 9]
  [4 3]]]

Tensor shape: (1, 3, 2)
3-Tensor:
[[[2 0]
  [3 9]
  [7 5]]]

